name: Sample Playwright API Call

on:
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call Sample Playwright Run API
        run: |
          curl --location 'https://beta8.moontechnolabs.com/tms-one-api/api/v1/playwright/run-tests-ciCD?id=276,275&projectId=&email=superadmin@yopmail.com'
