name: Sample Playwright API Call

on:
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call Sample Playwright Run API
        run: |
          curl --location 'https://f852a38f531c.ngrok-free.app/api/v1/playwright/run-tests-ciCD?id=364&projectId=&email=superadmin@yopmail.com'
